### ISSUE TITLE
Screen turns white in the Betweenlands when near active repeller

### ISSUE THREAD

**Issue by DoctorCJack** [TheCyberBrick/The-Betweenlands#1275]
#### Betweenlands version:

3.7.3

#### Forge version:

14.23.5.2855

#### Singleplayer or Multiplayer:

SinglePlayer

#### Installed mods:

Retested with only Betweenlands and JEI, still happens.

#### How to reproduce:

1. Place and activate repeller
2. Exist around it for a bit

#### Expected result:

Nothing happens, the screen should stay normal.

#### Actual result:

The screen occasionally turns white, either solid or flickering.

#### Pictures:

If a video would do, I can record and upload one if the screencap can see the glitch.

**Comment by DoctorCJack** [comment]
Update: This glitch appears to only happen above y=57 and I have no idea why.

**Comment by DoctorCJack** [comment]
I did some more experimenting and it seems to be location dependent, I don't know if it's caused by a nearby placed block or entity, but it stops happening in certain locations. I can upload a video if requested.

**Comment by SeriousCreeper** [comment]
Are you using Xaeros Worldmap and is there a Wind chime nearby? Those two things caused a white screen issue before. 
The latest version of Xaeros Worldmap should fix that issue however.

**Comment by DoctorCJack** [comment]
I do not have Xaeros Worldmap installed, is a wind chime from the Betweenlands mod and capable of spawning naturally? If yes to the second question, I could look around for it.

**Comment by SeriousCreeper** [comment]
They do not spawn naturally no. 
Could you try without BetterFPS and also Ootifine, see if one of them might cause this, to narrow it down?

**Comment by DoctorCJack** [comment]
I have tried without all the performance mods including Optifine, BetterFPS, Phosphor, etc, and a few others that affect the GUI like enhanced visuals. The problem persists with all of them removed. I will try removing some blocks I have placed in the area and see if I can isolate the block causing the problem. My first suspicion is going to be the repeller.

**Comment by DoctorCJack** [comment]
I have confirmed that it was in fact, the repeller causing the issue. I will now change the title of the issue to include the repeller detail.

**Comment by DoctorCJack** [comment]
Now I'm getting the glitch outside of the boat and spectator mode, I'm changing the title again because this is clearly an issue with the repeller exclusively.

**Comment by DoctorCJack** [comment]
I just found out that this is a duplicate of #1050. I will now close this issue.
